// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bidder_service.proto

package grpc

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BidderRegistrationRequest struct {
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	BankAccountNumber    string   `protobuf:"bytes,3,opt,name=bank_account_number,json=bankAccountNumber,proto3" json:"bank_account_number,omitempty"`
	BankName             string   `protobuf:"bytes,4,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidderRegistrationRequest) Reset()         { *m = BidderRegistrationRequest{} }
func (m *BidderRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*BidderRegistrationRequest) ProtoMessage()    {}
func (*BidderRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a4da2dc6039a8f, []int{0}
}

func (m *BidderRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidderRegistrationRequest.Unmarshal(m, b)
}
func (m *BidderRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidderRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *BidderRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidderRegistrationRequest.Merge(m, src)
}
func (m *BidderRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_BidderRegistrationRequest.Size(m)
}
func (m *BidderRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BidderRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BidderRegistrationRequest proto.InternalMessageInfo

func (m *BidderRegistrationRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *BidderRegistrationRequest) GetBankAccountNumber() string {
	if m != nil {
		return m.BankAccountNumber
	}
	return ""
}

func (m *BidderRegistrationRequest) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *BidderRegistrationRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type BidderRegistrationResponse struct {
	Data                 *BidderRegistrationRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Guid                 string                     `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BidderRegistrationResponse) Reset()         { *m = BidderRegistrationResponse{} }
func (m *BidderRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*BidderRegistrationResponse) ProtoMessage()    {}
func (*BidderRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a4da2dc6039a8f, []int{1}
}

func (m *BidderRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidderRegistrationResponse.Unmarshal(m, b)
}
func (m *BidderRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidderRegistrationResponse.Marshal(b, m, deterministic)
}
func (m *BidderRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidderRegistrationResponse.Merge(m, src)
}
func (m *BidderRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_BidderRegistrationResponse.Size(m)
}
func (m *BidderRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BidderRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BidderRegistrationResponse proto.InternalMessageInfo

func (m *BidderRegistrationResponse) GetData() *BidderRegistrationRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BidderRegistrationResponse) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func init() {
	proto.RegisterType((*BidderRegistrationRequest)(nil), "bidder_service.BidderRegistrationRequest")
	proto.RegisterType((*BidderRegistrationResponse)(nil), "bidder_service.BidderRegistrationResponse")
}

func init() {
	proto.RegisterFile("bidder_service.proto", fileDescriptor_a2a4da2dc6039a8f)
}

var fileDescriptor_a2a4da2dc6039a8f = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x09, 0x84, 0x8a, 0x9e, 0x42, 0x25, 0x0c, 0x43, 0x28, 0x4b, 0xc9, 0x54, 0x18, 0x32,
	0x94, 0x99, 0x81, 0x3e, 0x40, 0x87, 0xb0, 0xb1, 0x44, 0x4e, 0x72, 0x08, 0x16, 0x8d, 0x1d, 0x7c,
	0x61, 0xe0, 0x89, 0x78, 0x4c, 0xe4, 0x73, 0x60, 0x00, 0x81, 0x94, 0xcd, 0xfa, 0x2f, 0x9f, 0xfd,
	0xcb, 0x70, 0x5e, 0xab, 0xb6, 0x45, 0x5b, 0x39, 0xb4, 0x6f, 0xaa, 0xc1, 0x62, 0xb0, 0xc6, 0x1b,
	0x31, 0xff, 0xa9, 0xe6, 0x1f, 0x09, 0x5c, 0x6c, 0x48, 0x2a, 0xb1, 0x53, 0xce, 0x5b, 0xe9, 0x95,
	0xd1, 0x25, 0xbe, 0x06, 0x74, 0x5e, 0x5c, 0xc2, 0xf4, 0x29, 0xec, 0x76, 0x95, 0x96, 0x3d, 0x66,
	0xfb, 0xcb, 0x64, 0x35, 0x2d, 0x8f, 0xa2, 0xb0, 0x95, 0x3d, 0x8a, 0x02, 0xce, 0x6a, 0xa9, 0x5f,
	0x2a, 0xd9, 0x34, 0x26, 0x68, 0x5f, 0xe9, 0xd0, 0xd7, 0x68, 0xb3, 0x03, 0x8a, 0x9d, 0x46, 0xeb,
	0x9e, 0x9d, 0x2d, 0x19, 0x11, 0x46, 0x79, 0x82, 0xa5, 0x0c, 0x8b, 0x02, 0xc1, 0xae, 0xe0, 0x78,
	0x78, 0x36, 0x1a, 0xbf, 0x29, 0x87, 0xe4, 0xcf, 0x48, 0xe3, 0x7e, 0x6e, 0x60, 0xf1, 0xd7, 0x4b,
	0xdd, 0x60, 0xb4, 0x43, 0x71, 0x07, 0x69, 0x2b, 0xbd, 0xcc, 0x92, 0x65, 0xb2, 0x9a, 0xad, 0xaf,
	0x8b, 0x5f, 0xeb, 0xff, 0xdd, 0x58, 0x52, 0x4d, 0x08, 0x48, 0xbb, 0xa0, 0xda, 0xaf, 0x91, 0x74,
	0x5e, 0xbf, 0xc3, 0x09, 0xd7, 0x1e, 0x18, 0x22, 0x14, 0xcc, 0x99, 0x80, 0x96, 0x0d, 0x31, 0xfe,
	0x9e, 0xc5, 0xcd, 0x98, 0x28, 0x8f, 0xc9, 0xf7, 0x36, 0x93, 0xc7, 0xb4, 0xb3, 0x43, 0x53, 0x4f,
	0xe8, 0xdb, 0x6e, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x89, 0x53, 0xd2, 0x00, 0xce, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BidderServiceClient is the client API for BidderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BidderServiceClient interface {
	RegisterBidder(ctx context.Context, in *BidderRegistrationRequest, opts ...grpc.CallOption) (*BidderRegistrationResponse, error)
}

type bidderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBidderServiceClient(cc grpc.ClientConnInterface) BidderServiceClient {
	return &bidderServiceClient{cc}
}

func (c *bidderServiceClient) RegisterBidder(ctx context.Context, in *BidderRegistrationRequest, opts ...grpc.CallOption) (*BidderRegistrationResponse, error) {
	out := new(BidderRegistrationResponse)
	err := c.cc.Invoke(ctx, "/bidder_service.BidderService/RegisterBidder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BidderServiceServer is the server API for BidderService service.
type BidderServiceServer interface {
	RegisterBidder(context.Context, *BidderRegistrationRequest) (*BidderRegistrationResponse, error)
}

// UnimplementedBidderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBidderServiceServer struct {
}

func (*UnimplementedBidderServiceServer) RegisterBidder(ctx context.Context, req *BidderRegistrationRequest) (*BidderRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterBidder not implemented")
}

func RegisterBidderServiceServer(s *grpc.Server, srv BidderServiceServer) {
	s.RegisterService(&_BidderService_serviceDesc, srv)
}

func _BidderService_RegisterBidder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidderRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BidderServiceServer).RegisterBidder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bidder_service.BidderService/RegisterBidder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BidderServiceServer).RegisterBidder(ctx, req.(*BidderRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BidderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bidder_service.BidderService",
	HandlerType: (*BidderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterBidder",
			Handler:    _BidderService_RegisterBidder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bidder_service.proto",
}
